language: java
jdk:
- oraclejdk7
- oraclejdk8
branches:
  except:
    - www
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
before_install:
  - git fetch --depth=10000 origin
  - cp etc/gradle-ci.properties .
install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
  - bash /tmp/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda env create -q -f etc/env-linux.yml
  - source activate lenskit
  - ./gradlew ciPrep --stacktrace
script: ./gradlew ciTest --stacktrace --parallel
deploy:
  provider: script
  skip_cleanup: true
  script: etc/deploy.sh
  on:
    jdk: oraclejdk8
    repo: lenskit/lenskit
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/12b880d9f4086ef2a62c
    on_success: always
    on_failure: always
    on_start: always
  slack:
    rooms:
    - secure: "ldy/nkD8cNi3nNv8g+LEDmvsPKcKrHmuwctmCfc/kbmzmvmeG3DDa5RItSXnrmPGJhzbTEKKyrNIeA7U9awA7XYcZ7gSe7S5HogfCULrak2OYvLXVs69yQAP5ZuNF3c/AnuZz8rrE2UObMU22raZYrzrHM+LR7fUnurCaFq0S9w="
    on_pull_requests: false
env:
  global:
    - TERM=dumb
    - TZ=CST6CDT
sudo: false
