language: java
jdk:
- oraclejdk7
- oraclejdk8
branches:
  except:
  - www
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
  - $HOME/.local/lib/python2.7
before_install:
- pip install --user pandas
- git fetch --depth=10000 origin
install: ./gradlew ciPrep
script: ./gradlew ciTest
env:
  global:
  - TERM=dumb
  - TZ=CST6CDT
sudo: false
