version: 3.0.{build}
branches:
  only:
  - master
  - /release\/.*/
skip_tags: true
cache:
- C:\Users\appveyor\.gradle\wrapper
- C:\Users\appveyor\.gradle\caches
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0
install:
- etc\ci\av-setup.cmd
build_script:
- etc\ci\av-build.cmd
test_script:
- etc\av\av-setup.cmd
deploy: off
